# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YjiFireChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YjiFireChat
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'JSQMessagesViewController'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SnapKit'
  pod 'SQLite.swift', '~> 0.11.3'
end
